# Generated by Django 6.0 on 2025-12-14 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareerMentorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('preferred_mentor', models.CharField(max_length=200)),
                ('currentcareerstage', models.CharField(max_length=200)),
                ('goals', models.TextField()),
                ('anything_else', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Counseling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('preferred_counselor', models.CharField(max_length=200)),
                ('what_brings_you_here', models.TextField()),
                ('tell_us_more', models.TextField(blank=True, max_length=500)),
                ('preferred_schedule', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Learn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('currenteducation_level', models.CharField(max_length=200)),
                ('topics_of_interest', models.TextField()),
                ('other_topics', models.TextField(blank=True, max_length=500)),
                ('preffered_learning_style', models.CharField(max_length=200)),
                ('availability', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PeerMentorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('preferred_mentor', models.CharField(max_length=200)),
                ('age_range', models.CharField(max_length=100)),
                ('areaofgrowth', models.TextField()),
            ],
        ),
    ]
