# Generated by Django 6.0 on 2025-12-14 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careermentorship',
            name='anything_else',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='counseling',
            name='tell_us_more',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='learn',
            name='other_topics',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
