# Generated by Django 6.0 on 2025-12-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminAppForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128)),
                ('confirm_password', models.CharField(max_length=128)),
                ('reason_for_access', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='careerMentorshipForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('preferred_mentor', models.CharField(max_length=200)),
                ('currentcareerstage', models.CharField(max_length=200)),
                ('goals', models.TextField()),
                ('anything_else', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='contactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='counselingForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('preferred_counselor', models.CharField(max_length=200)),
                ('what_brings_you_here', models.TextField()),
                ('tell_us_more', models.TextField(blank=True, max_length=500)),
                ('preferred_schedule', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='learnForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('currenteducation_level', models.CharField(max_length=200)),
                ('topics_of_interest', models.TextField()),
                ('other_topics', models.TextField(blank=True, max_length=500)),
                ('preffered_learning_style', models.CharField(max_length=200)),
                ('availability', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='partnerAppForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('organization_name', models.CharField(max_length=200)),
                ('mission_statement', models.TextField()),
                ('password', models.CharField(max_length=128)),
                ('confirm_password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='peerMentorshipForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('preferred_mentor', models.CharField(max_length=200)),
                ('age_range', models.CharField(max_length=100)),
                ('areaofgrowth', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='sponsorAppForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=128)),
                ('confirm_password', models.CharField(max_length=128)),
                ('choose_amount', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='userAppForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=128)),
                ('confirm_password', models.CharField(max_length=128)),
            ],
        ),
        migrations.DeleteModel(
            name='FormSubmission',
        ),
    ]
