# Generated by Django 6.0 on 2025-12-14 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_careermentorship_anything_else_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('poster', models.CharField(blank=True, default='Anonymous', max_length=100, null=True)),
            ],
        ),
    ]
